region: us-west-2
gophish_certificate_id: 43a65aee-a035-4402-aee9-d1800ce754ec
landing_certificate_id: 6c0badf5-4a2f-42e7-b286-78c34b4ef6eb
status_certificate_id: 43fa71bd-3f77-4340-b017-1ac32f9c92d0
gophish_api_url: https://admin.phish.int.gdcorp.tools
sso_host: sso.gdcorp.tools
