region: us-west-2
gophish_certificate_id: 43a65aee-a035-4402-aee9-d1800ce754ec
landing_certificate_id: 255268bb-565b-4187-9ae3-b4d4ae797597
status_certificate_id: 43fa71bd-3f77-4340-b017-1ac32f9c92d0
gophish_api_url: https://admin.phish.int.gdcorp.tools
sso_host: sso.gdcorp.tools
