AWSTemplateFormatVersion: 2010-09-09
Description: PhishFramework Core Resources

Parameters:
  DevelopmentTeam:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for team owning the created resources.
    Default: /AdminParams/Team/Name
    AllowedValues:
      - /AdminParams/Team/Name
  DevelopmentEnvironment:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for development environment this will live in.
    Default: /AdminParams/Team/Environment
    AllowedValues:
      - /AdminParams/Team/Environment
  GophishCertificateId:
    Type: String
    Description: ACM Certificate ID for ALB in front of the admin service
    Default: ""
  LandingCertificateId:
    Type: String
    Description: ACM Certificate ID for ALB in front of the phish service
    Default: ""
  GophishAPIUrl:
    Type: String
    Description: Gophish API URL
    Default: ""
  GophishWebACLArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for Gophish WAFv2 Web ACL Arn
    Default: /Team/WAFv2/Regional/gophish/WebACLArn
    AllowedValues:
      - /Team/WAFv2/Regional/gophish/WebACLArn

Resources:
  FargateCluster:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: FargateCluster
      ProvisioningArtifactName: 1.1.0
      ProvisionedProductName: FargateCluster
      ProvisioningParameters:
        - Key: ClusterName
          Value: PhishFramework
      Tags:
        - Key: doNotShutDown
          Value: true

  GophishRepository:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: ECR
      ProvisioningArtifactName: 1.1.0
      ProvisionedProductName: GophishRepository
      ProvisioningParameters:
        - Key: ECRRepoName
          Value: gophish
      Tags:
        - Key: doNotShutDown
          Value: true

  GophishDBAdminCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: GophishDBAdminCredentials
      Description: Gophish DB cluster admin credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '$"@/\'

  GophishDBUserCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: GophishDBUserCredentials
      Description: Gophish DB cluster user credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "gophish"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '$"@/\'

  GophishPolicySecretsManager:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMPolicy
      ProvisioningArtifactName: 1.0.0
      ProvisionedProductName: GophishPolicySecretsManager
      ProvisioningParameters:
        - Key: PolicyNameSuffix
          Value: GophishPolicySecretsManager
        - Key: PolicyJSON
          Value: !Sub '{
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Action": "secretsmanager:GetSecretValue",
                    "Resource": "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GophishAPI*"
                },
                {
                    "Effect": "Allow",
                    "Action": "secretsmanager:GetSecretValue",
                    "Resource": "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GophishDBUserCredentials*"
                }
            ]
          }'
      Tags:
        - Key: doNotShutDown
          Value: true

  GophishTaskRole:
    DependsOn:
      - GophishPolicySecretsManager
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMRole
      ProvisioningArtifactName: 1.0.10
      ProvisionedProductName: GophishTaskRole
      ProvisioningParameters:
        - Key: RoleNameSuffix
          Value: TaskRole
        - Key: ManagedPolicyArns
          Value: !Join
            - ","
            -
              - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
              - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
              - !Sub arn:aws:iam::${AWS::AccountId}:policy/${DevelopmentTeam}-custom-GophishPolicySecretsManager
        - Key: AssumingServices
          Value: ecs-tasks.amazonaws.com
      Tags:
        - Key: doNotShutDown
          Value: true

  GophishTaskExecutionRole:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMRole
      ProvisioningArtifactName: 1.0.10
      ProvisionedProductName: GophishTaskExecutionRole
      ProvisioningParameters:
        - Key: RoleNameSuffix
          Value: TaskExecutionRole
        - Key: ManagedPolicyArns
          Value: !Join
            - ","
            -
              - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
              - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - Key: AssumingServices
          Value: ecs-tasks.amazonaws.com
      Tags:
        - Key: doNotShutDown
          Value: true

  GophishAPIUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Gophish/API/Url
      Type: String
      Value: !Ref GophishAPIUrl

  # https://github.com/gophish/user-guide/blob/master/installation.md#update-mysql-config
  GophishDBCluster:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Aurora
      ProvisioningArtifactName: 1.5.0
      ProvisionedProductName: GophishDBCluster
      ProvisioningParameters:
        - Key: MasterUsername
          Value: gdadministrator
        - Key: EngineFamily
          Value: aurora-mysql5.7
        - Key: InstanceType
          Value: serverless
        - Key: DatabaseClusterName
          Value: gophish
        - Key: CustomClusterParameterJSON
          Value: '{
            "sql_mode": "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
          }'
      Tags:
        - Key: doNotShutDown
          Value: true

  GophishService:
    DependsOn:
       - FargateCluster
       - GophishRepository
       - GophishTaskRole
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: FargateService
      ProvisioningArtifactName: 1.11.3
      ProvisionedProductName: GophishService
      ProvisioningParameters:
        - Key: ServiceName
          Value: gophish
        - Key: EnvironmentVariablesJson
          Value: '[{"Name": "MODE", "Value": "admin"}]'
        - Key: LoadBalancerVPCSubnetParamName
          Value: /AdminParams/VPC/DXAPPSubnets
        - Key: TrafficType
          Value: internal
        - Key: CertificateId
          Value: !Ref GophishCertificateId
        - Key: Cpu
          Value: 2048
        - Key: Memory
          Value: 4GB
        - Key: ContainerPort
          Value: 3333
        - Key: HealthCheckPath
          Value: /login
        - Key: WAFV2AclArn
          Value: !Ref GophishWebACLArn
        - Key: ClusterName
          Value: PhishFramework
        - Key: ECRRepo
          Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/gophish
        - Key: AllowDBAccess
          Value: true
        - Key: PrivateTaskVPCSubnetParamName
          Value: /AdminParams/VPC/DXAPPSubnets
        - Key: CustomIAMRoleNameSuffix
          Value: TaskRole
        - Key: RequiresIngress
          Value: true
        - Key: MinContainers
          Value: 1
        - Key: DesiredContainers
          Value: 1
        - Key: ContainerProtocol
          Value: HTTP
        - Key: AccessLogsEnabled
          Value: true
      Tags:
        - Key: doNotShutDown
          Value: false

  LandingService:
    DependsOn:
       - FargateCluster
       - GophishRepository
       - GophishTaskRole
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: FargateService
      ProvisioningArtifactName: 1.11.3
      ProvisionedProductName: LandingService
      ProvisioningParameters:
        - Key: ServiceName
          Value: landing
        - Key: EnvironmentVariablesJson
          Value: '[{"Name": "MODE", "Value": "phish"}]'
        - Key: LoadBalancerVPCSubnetParamName
          Value: /AdminParams/VPC/PublicSubnets
        - Key: TrafficType
          Value: internet-facing
        - Key: CertificateId
          Value: !Ref LandingCertificateId
        - Key: Cpu
          Value: 1024
        - Key: Memory
          Value: 2GB
        - Key: ContainerPort
          Value: 8080
        - Key: HealthCheckPath
          Value: /static/healthcheck.html
        - Key: ClusterName
          Value: PhishFramework
        - Key: ECRRepo
          Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/gophish
        - Key: AllowDBAccess
          Value: true
        - Key: PrivateTaskVPCSubnetParamName
          Value: /AdminParams/VPC/DXAPPSubnets
        - Key: CustomIAMRoleNameSuffix
          Value: TaskRole
        - Key: RequiresIngress
          Value: true
        - Key: MinContainers
          Value: 1
        - Key: DesiredContainers
          Value: 1
        - Key: ContainerProtocol
          Value: HTTP
        - Key: AccessLogsEnabled
          Value: true
      Tags:
        - Key: doNotShutDown
          Value: false
