AWSTemplateFormatVersion: 2010-09-09
Description: PhishFramework Aurora Database

Resources:
  GophishDBUserCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: GophishDBUserCredentials
      Description: Gophish DB cluster user credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "gophish"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '$"@/\'

  # https://github.com/gophish/user-guide/blob/master/installation.md#update-mysql-config
  GophishDBCluster:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Aurora
      ProvisioningArtifactName: 1.5.0
      ProvisionedProductName: GophishDBCluster
      ProvisioningParameters:
        - Key: MasterUsername
          Value: gdadministrator
        - Key: EngineFamily
          Value: aurora-mysql5.7
        - Key: InstanceType
          Value: serverless
        - Key: DatabaseClusterName
          Value: gophish
        - Key: CustomClusterParameterJSON
          Value: '{
            "sql_mode": "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
          }'
      Tags:
        - Key: doNotShutDown
          Value: true
