AWSTemplateFormatVersion: 2010-09-09
Description: PhishFramework Lambdas

Parameters:
  DevelopmentTeam:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for team owning the created resources.
    Default: /AdminParams/Team/Name
    AllowedValues:
      - /AdminParams/Team/Name
  DevelopmentEnvironment:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for development environment this will live in.
    Default: /AdminParams/Team/Environment
    AllowedValues:
      - /AdminParams/Team/Environment
  SSOHost:
    Type: String
    Description: SSO endpoint used by the status lambda
    Default: "sso.gdcorp.tools"
  DXVpcSecurityGroups:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for private dx app security group id
    Default: /AdminParams/VPC/PrivateDXAPPSG
    AllowedValues:
      - /AdminParams/VPC/PrivateDXAPPSG
  DXVpcSubnetIds:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Description: SSM Parameter for private dx app subnet ids
    Default: /AdminParams/VPC/DXAPPSubnets
    AllowedValues:
      - /AdminParams/VPC/DXAPPSubnets
  PreConfigLambdaHash:
    Type: String
    Description: SHA1 hash of the preconfig lambda source
    Default: ""
  PostConfigLambdaHash:
    Type: String
    Description: SHA1 hash of the postconfig lambda source
    Default: ""
  StatusLambdaHash:
    Type: String
    Description: SHA1 hash of the status lambda source
    Default: ""

Resources:
  PreConfigLambda:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Lambda
      ProvisioningArtifactName: 2.6.1
      ProvisionedProductName: PreConfigLambda
      ProvisioningParameters:
        - Key: S3Bucket
          Value: !Sub gd-${DevelopmentTeam}-${DevelopmentEnvironment}-code-bucket
        - Key: S3Key
          Value: !Sub preconfig/${PreConfigLambdaHash}
        - Key: Handler
          Value: preconfig.handler
        - Key: LambdaName
          Value: preconfig
        - Key: LambdaDescription
          Value: !Sub Security Exercise PreConfig lambda (${PreConfigLambdaHash})
        - Key: MemorySize
          Value: 256
        - Key: Runtime
          Value: python3.8
        - Key: Timeout
          Value: 60
        - Key: CustomIAMRoleNameSuffix
          Value: ConfigRole
        - Key: EnvironmentVariablesJson
          Value: !Sub '{"SSO_HOST": "${SSOHost}"}'
        - Key: VpcSecurityGroups
          Value: !Ref DXVpcSecurityGroups
        - Key: VpcSubnetIds
          Value: !Join [ ",", !Ref DXVpcSubnetIds ]
      Tags:
        - Key: doNotShutDown
          Value: true

  PostConfigLambda:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Lambda
      ProvisioningArtifactName: 2.6.1
      ProvisionedProductName: PostConfigLambda
      ProvisioningParameters:
        - Key: S3Bucket
          Value: !Sub gd-${DevelopmentTeam}-${DevelopmentEnvironment}-code-bucket
        - Key: S3Key
          Value: !Sub postconfig/${PostConfigLambdaHash}
        - Key: Handler
          Value: postconfig.handler
        - Key: LambdaName
          Value: postconfig
        - Key: LambdaDescription
          Value: !Sub Security Exercise PostConfig lambda (${PostConfigLambdaHash})
        - Key: MemorySize
          Value: 256
        - Key: Runtime
          Value: python3.8
        - Key: Timeout
          Value: 60
        - Key: CustomIAMRoleNameSuffix
          Value: ConfigRole
        - Key: EnvironmentVariablesJson
          Value: !Sub '{"SSO_HOST": "${SSOHost}"}'
        - Key: VpcSecurityGroups
          Value: !Ref DXVpcSecurityGroups
        - Key: VpcSubnetIds
          Value: !Join [ ",", !Ref DXVpcSubnetIds ]
      Tags:
        - Key: doNotShutDown
          Value: true

  StatusLambda:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Lambda
      ProvisioningArtifactName: 2.6.1
      ProvisionedProductName: StatusLambda
      ProvisioningParameters:
        - Key: S3Bucket
          Value: !Sub gd-${DevelopmentTeam}-${DevelopmentEnvironment}-code-bucket
        - Key: S3Key
          Value: !Sub status/${StatusLambdaHash}
        - Key: Handler
          Value: status.handler
        - Key: LambdaName
          Value: status
        - Key: LambdaDescription
          Value: !Sub Security Exercise Status lambda (${StatusLambdaHash})
        - Key: MemorySize
          Value: 256
        - Key: Runtime
          Value: python3.8
        - Key: Timeout
          Value: 15
        - Key: CustomIAMRoleNameSuffix
          Value: StatusRole
        - Key: EnvironmentVariablesJson
          Value: !Sub '{"SSO_HOST": "${SSOHost}"}'
        - Key: VpcSecurityGroups
          Value: !Ref DXVpcSecurityGroups
        - Key: VpcSubnetIds
          Value: !Join [ ",", !Ref DXVpcSubnetIds ]
      Tags:
        - Key: doNotShutDown
          Value: true
