region: us-west-2
gophish_certificate_id: b27d0958-d660-41a4-96f3-db0eaa378848
landing_certificate_id: d6c93702-e493-43b3-925e-27278725c986
status_certificate_id: e9ba043b-41ac-40a7-b3ae-0b31994267c2
gophish_api_url: https://admin.phish.int.dev-gdcorp.tools
sso_host: sso.dev-gdcorp.tools
