template_path: SC-CoreResources.yaml
dependencies:
  - {{environment}}/{{region}}/SC-CodeBucket.yaml
  - {{environment}}/{{region}}/SC-WAFv2Regional.yaml
parameters:
  GophishCertificateId: {{gophish_certificate_id}}
  LandingCertificateId: {{landing_certificate_id}}
  GophishAPIUrl: {{gophish_api_url}}
