name: Deployment (PROD)

# Deploys the PhishFramework main branch to the AWS PROD environment
# using sceptre.

on:
  workflow_dispatch:

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Set up Python 3.8
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: 3.8
          architecture: 'x64'

      - name: Setup Python Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip

      - name: Install Python dependencies
        env:
          SECURESERVER_ACCESS_KEY: ${{ secrets.SECURESERVER_ACCESS_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SECURESERVER_ACCESS_KEY}"
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt -r requirements-test.txt
          ssh-agent -k

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::717081260494:role/GD-AWS-USA-CTO-Phish-Prod-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2

      - name: Run sceptre
        env:
          SECURESERVER_ACCESS_KEY: ${{ secrets.SECURESERVER_ACCESS_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SECURESERVER_ACCESS_KEY}"
          source venv/bin/activate
          cd sceptre
          sceptre launch -y prod/us-west-2
          ssh-agent -k
