name: Deployment (DEV-PRIVATE)

# Deploys the PhishFramework main branch to the AWS DEV-PRIVATE environment
# using sceptre.

# For now, can only be deployed manually through workflow_dispatch - Select
# your branch while running

on:
  workflow_dispatch:

jobs:
  deploy_to_dev_private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Set up Python 3.8
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: 3.8
          architecture: 'x64'

      - name: Setup Python Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip

      - name: Install Python dependencies
        env:
          SECURESERVER_ACCESS_KEY: ${{ secrets.SECURESERVER_ACCESS_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SECURESERVER_ACCESS_KEY}"
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt -r requirements-test.txt
          ssh-agent -k

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::911872167152:role/GD-AWS-USA-CTO-Phish-Dev-Private-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2

      - name: Run sceptre
        env:
          SECURESERVER_ACCESS_KEY: ${{ secrets.SECURESERVER_ACCESS_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SECURESERVER_ACCESS_KEY}"
          source venv/bin/activate
          cd sceptre
          sceptre launch -y dev-private/us-west-2
          ssh-agent -k
