name: Hash PII Data (PROD)

# Will connect to the Database and hash the email addresses in there
# to remove any PII in the platform

# This workflow is supposed to be run manually after the end of every campaign/
# gambit as part of the playbook for phishing campaigns

on:
  workflow_dispatch:

jobs:
  hash_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::717081260494:role/GD-AWS-USA-CTO-Phish-Prod-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2

      - name: Set up Python 3.8
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: 3.8
          architecture: 'x64'

      - name: Connect to the MySQL DB and hash PII using MD5
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          python -m pip install awscli
          sh -x tools/hash_user_data.sh
