name: Container Rotation

# Rotates containers by forcing a redeployment once per day.  This is to
# satisfy the requirement that containers have a maximum runtime of 24 hours.

# This workflow can be deployed manually through workflow_dispatch; but will
# always be run at 3:08 AM UTC.

on:
  schedule:
    - cron: "8 3 * * *"
  workflow_dispatch:

jobs:
  rotate_dev_private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::911872167152:role/GD-AWS-USA-CTO-Phish-Dev-Private-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2

      - name: Set up Python 3.8
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: 3.8
          architecture: 'x64'

      - name: Setup python environment and force redeployment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          python -m pip install awscli
          sh -x tools/update_service.sh

  rotate_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::717081260494:role/GD-AWS-USA-CTO-Phish-Prod-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2

      - name: Set up Python 3.8
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: 3.8
          architecture: 'x64'

      - name: Setup python environment and force redeployment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip
          python -m pip install awscli
          sh -x tools/update_service.sh
